-- MySQL Script generated by MySQL Workbench
-- Wed Jun  7 10:30:18 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema onepass
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `onepass` ;

-- -----------------------------------------------------
-- Schema onepass
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `onepass` DEFAULT CHARACTER SET utf8 ;
USE `onepass` ;

-- -----------------------------------------------------
-- Table `onepass`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `onepass`.`user` ;

CREATE TABLE IF NOT EXISTS `onepass`.`user` (
`id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
`email` VARCHAR(45) NOT NULL,
`secret_key` VARCHAR(45) NULL,
PRIMARY KEY (`id`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `onepass`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `onepass`.`category` ;

CREATE TABLE IF NOT EXISTS `onepass`.`category` (
`id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
`name` VARCHAR(45) NULL,
`user_id` INT UNSIGNED NOT NULL,
PRIMARY KEY (`id`, `user_id`),
INDEX `fk_category_user1_idx` (`user_id` ASC),
CONSTRAINT `fk_category_user1`
FOREIGN KEY (`user_id`)
REFERENCES `onepass`.`user` (`id`)
ON DELETE NO ACTION
ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `onepass`.`credentials`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `onepass`.`credentials` ;

CREATE TABLE IF NOT EXISTS `onepass`.`credentials` (
`id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
`username` VARCHAR(45) NULL,
`password` VARCHAR(45) NULL,
`url` VARCHAR(45) NULL,
`email` VARCHAR(45) NULL,
`notice` VARCHAR(45) NULL,
`category_id` INT UNSIGNED NOT NULL,
`user_id` INT UNSIGNED NOT NULL,
PRIMARY KEY (`id`, `user_id`),
INDEX `fk_credentials_category_idx` (`category_id` ASC),
INDEX `fk_credentials_user1_idx` (`user_id` ASC),
CONSTRAINT `fk_credentials_category`
    FOREIGN KEY (`category_id`)
        REFERENCES `onepass`.`category` (`id`)
        ON DELETE NO ACTION
        ON UPDATE NO ACTION,
CONSTRAINT `fk_credentials_user1`
    FOREIGN KEY (`user_id`)
        REFERENCES `onepass`.`user` (`id`)
        ON DELETE NO ACTION
        ON UPDATE NO ACTION)
    ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- Testdata for table `user`
INSERT INTO `user` (`email`, `secret_key`) VALUES
('user1@example.com', 'secret1'),
('user2@example.com', 'secret2'),
('user3@example.com', 'secret3');

-- Testdata for table `category`
INSERT INTO `category` (`name`, `user_id`) VALUES
('Category 1', 1),
('Category 2', 1),
('Category 3', 2),
('Category 4', 2),
('Category 5', 3);

-- Testdata for table `credentials`
INSERT INTO `credentials` (`username`, `password`, `url`, `email`, `notice`, `category_id`, `user_id`) VALUES
('user1', 'password1', 'https://example.com', 'user1@example.com', 'Note 1', 1, 1),
('user2', 'password2', 'https://example.com', 'user2@example.com', 'Note 2', 1, 1),
('user3', 'password3', 'https://example.com', 'user3@example.com', 'Note 3', 2, 1),
('user4', 'password4', 'https://example.com', 'user4@example.com', 'Note 4', 2, 1),
('user5', 'password5', 'https://example.com', 'user5@example.com', 'Note 5', 3, 2);
