-- MySQL Script generated by MySQL Workbench
-- Mon Jun  5 10:09:09 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema onepass
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `onepass` ;

-- -----------------------------------------------------
-- Schema onepass
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `onepass` DEFAULT CHARACTER SET utf8 ;
USE `onepass` ;

-- -----------------------------------------------------
-- Table `onepass`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `onepass`.`user` ;

CREATE TABLE IF NOT EXISTS `onepass`.`user` (
  `iduser` INT UNSIGNED NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `secret_key` VARCHAR(45) NULL,
  PRIMARY KEY (`iduser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `onepass`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `onepass`.`category` ;

CREATE TABLE IF NOT EXISTS `onepass`.`category` (
  `id` INT UNSIGNED NOT NULL,
  `name` VARCHAR(45) NULL,
  `user_iduser` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `user_iduser`),
  INDEX `fk_category_user1_idx` (`user_iduser` ASC) VISIBLE,
  CONSTRAINT `fk_category_user1`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `onepass`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `onepass`.`credentials`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `onepass`.`credentials` ;

CREATE TABLE IF NOT EXISTS `onepass`.`credentials` (
  `id` INT UNSIGNED NOT NULL,
  `username` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `url` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `notice` VARCHAR(45) NULL,
  `category_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_credentials_category_idx` (`category_id` ASC) VISIBLE,
  CONSTRAINT `fk_credentials_category`
    FOREIGN KEY (`category_id`)
    REFERENCES `onepass`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
